from wasm.module import Module
from wasm.type import TypeSection
from wasm.type import TypeEntry
from wasm.impo import ImportSection
from wasm.impo import ImportEntry
from wasm.memory import MemorySection
from wasm.memory import MemoryEntry
from wasm.glob import GlobalSection
from wasm.glob import GlobalEntry
from wasm.table import TableSection
from wasm.table import TableEntry
from wasm.data import DataSection
from wasm.data import DataEntry
from wasm.elem import ElemSection
from wasm.elem import ElemEntry
from wasm.export import ExportSection
from wasm.export import ExportEntry
from wasm.code import CodeSection
from wasm.code import CodeEntry
from wasm.function import FunctionSection
from wasm.function import FunctionEntry
from wasm.user import UserSection
from wasm.const import *
