from utils import varuint

SECTION_TYPE = 1
SECTION_IMPORT = 2
SECTION_FUNCTION = 3
SECTION_TABLE = 4
SECTION_MEMORY = 5
SECTION_GLOBAL = 6
SECTION_EXPORT = 7
SECTION_START = 8
SECTION_ELEMENT = 9
SECTION_CODE = 10
SECTION_DATA = 11
SECTION_USER = 0

TYPE_i32 = 0x7f
TYPE_i64 = 0x7e
TYPE_f32 = 0x7d
TYPE_f64 = 0x7c
TYPE_FUNC = 0x60
TYPE_ANYFUNC = 0x70

KIND_FUNCTION = 0
KIND_TABLE = 1
KIND_MEMORY = 2
KIND_GLOBAL = 3

def CONST_i32(value):
    return varuint(0x41) + varuint(value) + '\x0b'

def CONST_i64(value):
    return varuint(0x42) + varuint(value) + '\x0b'

MUTABLE = 1
IMMUTABLE = 0
